---
# file: tasks/install-git.yml

- name: Install IUS release package
  yum:
    name: https://repo.ius.io/ius-release-el7.rpm
    state: present

- name: Disable IUS repository
  ini_file:
    path: /etc/yum.repos.d/ius.repo
    section: ius
    option: enabled
    value: '0'

- name: Remove old version of Git
  yum:
    name: git
    state: absent

- name: Install new version of Git
  yum:
    name: git236
    state: present
    enablerepo: ius

